### ISSUE TITLE
Python3 failed to execute

### ISSUE THREAD

**Issue by BurritoWrapped** [blha303/gitlab-discord-bridge#1]
Error:

```
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    config = json.load(f)
  File "/usr/local/lib/python3.5/dist-packages/flask/json.py", line 158, in load
    return _json.load(fp, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 23 (char 22)

```

**Comment by blha303** [comment]
Your config file is not valid json.
